[package]
name = "frs"
version = "0.2.0"
authors = ["ZSchoen <dev@zschoen.dev>"]
edition = "2018"
license = "MIT"
readme = "README.md"
homepage = "https://zschoen.dev/projects/frs"
repository = "https://github.com/TheAlgorythm/frs"
description = "Rename files with RegEx patterns"
keywords = ["rename", "find", "regex", "rename-files", "rename-directories"]
categories = ["command-line-utilities", "filesystem", "development-tools"]

[dependencies]
futures = "0.3"
async-std = { version = "1.9", features = ["attributes"] }
regex = "1.4"
structopt = "0.3"
colored = "2.0"

[dev-dependencies]
matches = "0.1"
maplit = "1.0"

